### ISSUE TITLE
There is one little bug in UI (Details inside)

### ISSUE THREAD

**Issue by NomanBaigA** [imsudip/minfo#1]
In app UI there is something strange is showing up (Screenshot included)

Error message - "Bottom overflowed by 49 pixels"

The app is unique and works fine. Good Work 

Screenshot - 
![Screenshot](https://github.com/imsudip/minfo/assets/49509445/fcecebd2-67e4-4d8c-b859-8ac2eb068970)

**Comment by imsudip** [comment]
Thanks for raising the issue, and I'm glad you find the app unique and working fine otherwise! 😄

Ah, the notorious "Bottom overflowed" error, a classic gem! It seems like the code might have had a little too much fun with the pixels and decided to go on a joyride. But don't worry, I'll hop in, put on my detective hat, and investigate the situation ASAP!

If you have any other observations or ideas, feel free to share them

**Comment by NomanBaigA** [comment]
> Thanks for raising the issue, and I'm glad you find the app unique and working fine otherwise! 😄
> 
> Ah, the notorious "Bottom overflowed" error, a classic gem! It seems like the code might have had a little too much fun with the pixels and decided to go on a joyride. But don't worry, I'll hop in, put on my detective hat, and investigate the situation ASAP!
> 
> If you have any other observations or ideas, feel free to share them

Thanks for the response. I fixed this issue and sent a pull request (Verify, Test, and Merge)

**Comment by NomanBaigA** [comment]
Fixed
